development:
  adapter: postgresql
  encoding: unicode
  database: learnby_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: learnby_test
  pool: 5
  username: postgres
  password: postgres
